version: '3'

services:
  django:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000" # && gunicorn jyn_pathshala.wsgi:application -b 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      # - mysql
    networks:
      - backend

  celery:
    build: .
    command: bash -c "celery -A jyn_pathshala worker -l info & celery -A jyn_pathshala beat -l info & celery -A jyn_pathshala flower"
    volumes:
      - .:/usr/src/app
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: "redis:latest"
    networks:
      - backend

  # FOR NOW WE ARE USING SQLITE3 ONLY
  # mysql: 
  #   image: "mysql:latest"
  #   environment:
  #     MYSQL_DATABASE: db_jain_youth_noida
  #     # MYSQL_USER: root
  #     MYSQL_PASSWORD: JainYouthNoida@2012
  #     MYSQL_ROOT_PASSWORD: JainYouthNoida@2012
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge
